FROM gcr.io/tensorflow/tensorflow:latest-py3
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN ${GITHUB_TOKEN}

RUN apt update && apt-get install -y \
	ffmpeg \
	git

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -U pip
RUN pip install -r ./requirements.txt
RUN pip install git+https://${GITHUB_TOKEN}@github.com/nowthisnews/ds-transform.git


WORKDIR /workspace
