FROM gcr.io/tensorflow/tensorflow:latest-py3

RUN apt update && apt-get install -y ffmpeg 

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -U pip
RUN pip install -r ./requirements.txt

WORKDIR /workspace
